library(shiny)

report_tab <- tabPanel(
  "Report",
  titlePanel("Report"),
  mainPanel(
    tags$div("Project Title: Broadband Effect on Education",
             tags$br(),
             tags$br(),
             "Authors: Hanna Lee, Daniel Lee, Nick Vaughn, John Nguyen",
             tags$br(),
             tags$br(),
             "Affiliation: University of Washington",
             tags$br(),
             tags$br(),
             "Date: 03 / 04 / 2022"),
    tags$br(),
    tags$div("Key Words:",
             tags$br(),
             "1) Broadband",
             "2) Equitable Education",
             "3) Accessibility"),
    tags$br(),
    tags$div("Abstract:",
             tags$br(),
             tags$br(),
             "We are concerned with inequity in students having broadband access because it may disadvantage many students as education relies more on technology. To address this concern, we plan to analyze multiple datasets on student state assessment performance in Washington and see if there is a correlation between their performance and broadband access."),
    tags$br(),
    tags$div("Introduction:",
             tags$br(),
             tags$br(),
             "Education is fundamental to our growth whether it's done in a classroom setting or in our homes. As our society gravitates towards a technology-based empire, broadband must grow with our needs to prevent unbalanced progress. During the pandemic, this was highlighted when children were left to study at restaurants and parking lots with free Wi-Fi. The prevalent imbalance showcased the privilege of having expendable income for broadband and having access to reliable broadband. Our primary focus is on students and their academic status in the school year 2016-17, and our broadband data is from 2016. We will analyze broadband access within the different geographic areas within the US and see if there's a correlation between student academic growth and broadband access."),
    tags$br(),
    tags$div("Project Framing:",
             tags$br(),
             tags$br(),
             "Education enables individuals to build more prosperous lives and societies to achieve economic prosperity. In the modern world, education is closely intertwined with the Internet. The Internet enhances the educational experience in innumerable ways: it provides a wealth of information, increases opportunities for learning, and provides powerful tools to support the learning experience (Internet Society, 2017).",
             tags$br(),
             tags$br(),
             "However, the Internet's educational benefits inherently create a disparity between students who have Internet access and those who do not. Not every student has equal access to the Internet. While an impressive 99 percent of US public schools have access to the Internet (NCES, n.d.), many developing nations struggle to provide even a traditional classroom education. In his book Outliers, author Malcolm Gladwell describes the biblically eponymous \"Matthew Effect\"- advantages compound gains while disadvantages compound losses (Gwinn, 2008). In the same vein, students with Internet access will further their education, while those with minimal access will fall behind. This snowball effect can widen social and economic disparities amongst nations, social classes, and other groups."
    ),
    tags$br(),
    tags$div("Human Values:",
             tags$br(),
             tags$br(),
             "Equality: The Internet's disparate impact on education is fundamentally a matter of equality. Varying levels of Internet access inherently create unequal learning environments, which results in unequal future opportunities. The main goal is to bridge this educational gap.",
             tags$br(),
             tags$br(),
             "Opportunity / Well-being: Students with minimal access to the Internet are likely to have worse educational experiences and thus lesser future opportunities than their peers. We should aspire to provide them the opportunity to have an Internet-based education.",
             tags$br(),
             tags$br(),
             "Value Tensions: In order to seek equality in education, we should ideally provide opportunities to students with minimal Internet access. However, it is possible to seek equality in the opposite direction - by denying the Internet from students currently utilizing it. This may result in more equality, but lessen opportunities for the bereft students and compromise their well-being."),
    tags$br(),
    tags$div("Direct Stakeholders:",
             tags$br(),
             tags$br(),
             "Educational Institutions: Educational institutions are ultimately responsible for providing their students the best education possible. If data unequivocally proves that Internet access is indispensable to a superb education, they will be incentivized to provide Internet access to their students.",
             tags$br(),
             tags$br(),
             "Education Rights Groups: These organizations have a mission to make education accessible. If a lack of Internet access renders traditional education obsolete, then these organizations will strive to make Internet-based education accessible."
    ),
    tags$br(),
    tags$div("Indirect Stakeholders:",
             tags$br(),
             tags$br(),
             "Underprivileged Students: Internet access will improve their quality of education and provide better future opportunities.",
             tags$br(),
             tags$br(),
             "Society: If Internet access bolsters more students' education, then economic output will increase in the long run.",
             tags$br(),
             tags$br(),
             "Families: They would be able to see one their own members receive quality education.",
             tags$br(),
             tags$br(),
             "Privileged students: If other students are granted an Internet-based education, this may increase academic competition for the incumbent privileged students."
    ),
    tags$br(),
    tags$div("Benefits:",
             tags$br(),
             tags$br(),
             "1. We may establish equality in education and welfare amongst people.",
             tags$br(),
             tags$br(),
             "2. We can create more educated citizens, which in turn will lead to increased economic output and a more well-functioning society in the long run."
    ),
    tags$br(),
    tags$div("Harms:",
             tags$br(),
             tags$br(),
             "1. While Internet access would provide opportunities to underprivileged students, the incumbent privileged students would likely suffer from higher competition.",
             tags$br(),
             tags$br(),
             "2. Organizations may decide to limit Internet access to students who already have it. This is fairly easy to implement since it involves taking resources away rather than providing them. However, this would harm the education of students already benefiting from Internet access and may indirectly impact society as a whole."
    ),
    tags$br(),
    tags$div("Research Questions:",
             tags$br(),
             tags$br(),
             "1. Does limited broadband access impact on test satisfactory levels?",
             tags$br(),
             tags$br(),
             "2. Is broadband access a factor in the different test subject performance?",
             tags$br(),
             tags$br(),
             "3. Does English as a second language students performance differ based on broadband speeds?"
    ),
    tags$br(),
    tags$div("The Dataset:",
             tags$br(),
             tags$br(),
            "1) Report Card Assessment Data 2016-2017 School Year",
            tags$br(),
            tags$br(),
            "- 951,000 observations and 30 variables",
            tags$br(),
            "- We have student state assessment data of various subjects from kindergarten to 12th grade.",
            tags$br(),
            "- The dataset has multiple identifiers for schools, breakdown of student demographics, different subjects, expected outcomes, and actual standing (satisfactory/unsatisfactory) of student grade/group.",
            tags$br(),
            "- Age of student group and various test scores were left out. Instead the dataset categorized the students as satisfactory or unsatisfactory in the subject matter",
            tags$br(),
            "- Washington Office of Superintendent of Public Instruction created the dataset on September 12, 2019. They own and update the dataset according to data.gov.",
            tags$br(),
            "- Educators and any field can make money off student data because they can create supplemental resources if they find students facing difficulties in certain subjects and tailor it to the students groups/grade having the issue.",
            tags$br(),
            "- The data is housed and hosted on a government website which provides added protection. The validity of the data is through direct student information data, so we confident in the outcomes.",
            tags$br(),
            "- We found this dataset through Data.gov. The citation is listed in references.",
            tags$br(),
            tags$br(),
            "2) June 2016 FCC Area Table",
            tags$br(),
            tags$br(),
            "- 178,992 observations and 7 variables",
            tags$br(),
            "- The dataset shows the broadband coverage in geographic areas throughout the country.",
            tags$br(),
            "- Each observation reveals the type of area, ID of area, the technology of broadband, urban/rural, tribal/nontribal, download speeds, and the number of providers. We don't see the average price or who the providers are.",
            tags$br(),
            "- It is unclear who collected the data, but the owner is Humza Riaz. It was created on March 18, 2018 and reveals the general broadband accessibility in this country.",
            tags$br(),
            "- This is raw data from the FCC's broadband website which has an interactive map feature that tracks various points of broadband usage in the country.",
            tags$br(),
            "- The origin of funding is unclear, but FCC is part of the federal government.",
            tags$br(),
            "- This data can allow for greater accessibility to broadband or highlight price gouging to users in rural areas.",
            tags$br(),
            "- The data was collected through surveys and public broadband information. It is credible since it's reporting hard data, but surveys are never 100%.",
            tags$br(),
            "- We found this dataset through Data.gov. The citation is listed in references.",
            tags$br(),
            tags$br(),
            "3) 2020 FCC Geography Lookup",
            tags$br(),
            tags$br(),
            "- 22,514,373 observations and 10 variables",
            tags$br(),
            "- This was our reference guide for the FCC Area Table because the ID of Area was coded as a number.",
            tags$br(),
            "-	Since this was our decoder and only stated the longitude, latitude, and name of the area, we did not question the validity of the data.",
            tags$br(),
            "- The table was updated on April 8, 2021",
            tags$br(),
            "-	We found this dataset through Data.gov. The citation is listed in references."
    ),
    tags$br(),
    tags$div("1) Does limited broadband access impact test satisfactory levels?",
             tags$br(),
             tags$br(),
             "Our initial hypothesis was that limited broadband access would predictably lower test levels. We used two proxies for broadband access - internet speed and access points. We attempted to establish correlations between the two proxy variables and test levels. Our analysis resulted in slightly negative correlations, thereby opposing our hypothesis. However, there were several extenuating circumstances. First, correlation does not prove causation, and we would need further tests such as controlled experiments to confirm a causal relationship. Second, the quantity of data was a bit sparse and the strength of the correlation is therefore not as robust. Moreover, the correlation could have easily been positive if not for a couple of outliers. In short, our analysis suggests a negative correlation between broadband access and test levels, but further analysis with more data is required to conclusively support that.", 
             tags$br(),
             tags$br(),
             "2) Is broadband access a factor in the different test subject performance?",
             tags$br(),
             tags$br(),
             "Our initial hypothesis was that limited broadband access would negatively affect test levels in all subjects, since the Internet provides helpful resources in almost any domain. We attempted to break down the correlations between having generally acceptable broadband access and test levels by specific school subjects. The correlations for five different subjects were all slightly negative or close to zero. Our analysis suggests that broadband access has minimal impact on test levels in any subject. However, we would need to analyze more datasets to conclusively support that theory.",
             tags$br(),
             tags$br(),
             "3) Does English as a second language students' performance differ based on broadband speeds?",
             tags$br(),
             tags$br(),
             "Our initial hypothesis was that limited broadband access would severely hurt the test levels of English language learners, since it would add another handicap to their language deficiencies. We attempted to establish correlations between having generally acceptable broadband access and test levels for English language learners, further breaking it down by middle school and high school students. There were a few signs of positive correlation, but overall there are no conclusive trends in the data. Moreover, we lacked sufficient data for 9th and 12th grade high schoolers. Unfortunately, the results are inconclusive to answer the question."
    )
  )
)

